### ISSUE TITLE
Question on scaling video

### ISSUE THREAD

**Issue by freiguy1** [imager-io/ffmpeg-dev-rs#6]
Hi there. This isn't an actual issue, but more of a question. I hope that's ok.

I'm working on a project to reduce the disk space required by mp4 videos. I was planning on doing this by scaling down the resolution and lowering frames per second.  I'm doing this with Rust, and my searching directed me to ffmpeg. This is my first exposure to ffmpeg.

Am I on the right track by using this library in the first place? If not, you can stop reading here and say so.

 I found [an ffmpeg example](https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/scaling_video.c) about scaling, but I'll be honest, it seems more complicated than I was expecting especially when just using the command line ffmpeg tool can scale with this command:

`ffmpeg -i input.avi -vf scale=320:240 output.avi`

Can you point me in the right direction for doing these operations (scaling and lowering fps)? Perhaps some pseudo code would be helpful. Thanks!

**Comment by colbyn** [comment]
Yes, use the CLI interface. Especially if you are new to rust, this library isn't idiomatic or safe rust code. 

Some time ago when I was a JR dev working on a video processing project, I tried to use FFmpeg VIA the C APIs over some CLI interface, the result was terrible. Furthermore using the CLI interface would have been substantially easier and more robust.

So regarding your question on implementation and my aforementioned mistake. :)

I'd just use `std::process::Command` ([api docs](https://doc.rust-lang.org/std/process/struct.Command.html)) from the standard library, this will allow you to invoke FFmpeg as a child process using its CLI interface. You can even batch multiple encoding instances  in a single invocation or whatever it's called. 

Regarding your question on compression, this is a bit more complicated, and I'm not sure about the requirements of your project (also I'm not an expert on video compression, and especially anything related to audio)...

First, I think, you can't really talk about compression in this context without regard for any specific video codec. For instance, whereas JPEG generally refers to a container format and codec, MP4 files may contain an H264/AVC encoded video stream, or something different, such as the newer H265/HEVC video codec, which may make for a substantial difference with regards to quality/file-size tradeoffs. Anyway If you writing such a tool, I'd first consider what video codecs you need to support, not just the container format. Thereafter I'd dive into the more technical aspects on how the given encoder works and it's exposed settings and whatnot, since otherwise you'll probably be using subpar defaults, unknowingly.

Hope this helps.

**Comment by freiguy1** [comment]
Thanks much. The CLI it is for me!
